name: Master - build, test, & release Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Test with Maven
        run: mvn -B test --file pom.xml
      - name: Verify with Maven
        run: mvn -B verify --file pom.xml
      - name: Release with Maven
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "master"
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@github.com"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          skip-perform: true

