name: PR - build & test Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Test with Maven
        run: mvn -B test --file pom.xml
      - name: Verify with Maven
        run: mvn -B verify --file pom.xml
